In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import glob
import pandas as pd
from PIL import Image
from PIL.ExifTags import TAGS

path="/content/drive/My Drive/Final Year Research/Dataset/Oneplus 5T/Level 04/*"
len_str_remove=len(path)-1
df = pd.DataFrame(columns=['image', 'brightness','shutter_speed','iso'])
i=0
for file in glob.glob(path):
    #print(file[len_str_remove:])
    img = Image.open(file)
    # extract EXIF data
    exifdata = img.getexif()
    img_mdata=np.zeros(3)
    # iterating over all EXIF data fields
    for tag_id in exifdata:
        # get the tag name, instead of human unreadable tag id
        tag = TAGS.get(tag_id, tag_id)
        data = exifdata.get(tag_id)
        # decode bytes 
        if isinstance(data, bytes):
            data = data.decode()
        #print(f"{tag:25}: {data}")
        if(tag=='BrightnessValue'):
          img_mdata[0]=data[0]/data[1]
        
        if(tag=='ShutterSpeedValue'):
          img_mdata[1]=data[0]/data[1]

        if(tag=='ISOSpeedRatings'):
          img_mdata[2]=data

    df.loc[i] = [file[len_str_remove:]] + [img_mdata[0]] + [img_mdata[1]] + [img_mdata[2]]
    i+=1
    if(i==150):break

print(df.shape)
df

(150, 4)

                       image  brightness  shutter_speed    iso
0    IMG_20210721_095141.jpg        4.85          8.976  100.0
1    IMG_20210721_095142.jpg        4.92          9.066  125.0
2    IMG_20210721_095144.jpg        4.93          9.109  125.0
3    IMG_20210721_095145.jpg        5.03          9.193  100.0
4    IMG_20210721_095146.jpg        5.04          9.193  100.0
..                       ...         ...            ...    ...
145  IMG_20210721_100042.jpg        5.22          9.323  125.0
146  IMG_20210721_100050.jpg        5.03          9.109  125.0
147  IMG_20210721_100053.jpg        5.01          9.066  125.0
148  IMG_20210721_100123.jpg        5.16          9.193  100.0
149  IMG_20210721_100125.jpg        5.35          9.534  100.0

[150 rows x 4 columns]

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import glob
import pandas as pd
from PIL import Image
from PIL.ExifTags import TAGS

path="/content/drive/My Drive/Final Year Research/Dataset/Oneplus 5T/Level 03/*"
len_str_remove=len(path)-1

i=0
for file in glob.glob(path):
    #print(file[len_str_remove:])
    img = Image.open(file)
    # extract EXIF data
    exifdata = img.getexif()
    img_mdata=np.zeros(3)
    # iterating over all EXIF data fields
    for tag_id in exifdata:
        # get the tag name, instead of human unreadable tag id
        tag = TAGS.get(tag_id, tag_id)
        data = exifdata.get(tag_id)
        # decode bytes 
        if isinstance(data, bytes):
            data = data.decode()
        #print(f"{tag:25}: {data}")
        if(tag=='BrightnessValue'):
          img_mdata[0]=data[0]/data[1]
        
        if(tag=='ShutterSpeedValue'):
          img_mdata[1]=data[0]/data[1]

        if(tag=='ISOSpeedRatings'):
          img_mdata[2]=data

    df.loc[150+i] = [file[len_str_remove:]] + [img_mdata[0]] + [img_mdata[1]] + [img_mdata[2]]
    i+=1
    if(i==150):break

print(df.shape)
df

(300, 4)

                       image  brightness  shutter_speed    iso
0    IMG_20210721_095141.jpg        4.85          8.976  100.0
1    IMG_20210721_095142.jpg        4.92          9.066  125.0
2    IMG_20210721_095144.jpg        4.93          9.109  125.0
3    IMG_20210721_095145.jpg        5.03          9.193  100.0
4    IMG_20210721_095146.jpg        5.04          9.193  100.0
..                       ...         ...            ...    ...
295  IMG_20210721_102756.jpg        5.12          9.024  125.0
296  IMG_20210721_102758.jpg        5.12          9.024  125.0
297  IMG_20210721_102759.jpg        5.15          9.024  125.0
298  IMG_20210721_102801.jpg        5.15          8.976  100.0
299  IMG_20210721_102802.jpg        5.08          8.936  125.0

[300 rows x 4 columns]

In [ ]:
df.to_csv('metadata.csv',index=False)
!cp metadata.csv "drive/My Drive/Final Year Research/Dataset/Oneplus 5T/data_in_csv_backup/"

In [ ]:
data=pd.read_csv('metadata.csv')
data

                       image  brightness  shutter_speed    iso
0    IMG_20210721_095141.jpg        4.85          8.976  100.0
1    IMG_20210721_095142.jpg        4.92          9.066  125.0
2    IMG_20210721_095144.jpg        4.93          9.109  125.0
3    IMG_20210721_095145.jpg        5.03          9.193  100.0
4    IMG_20210721_095146.jpg        5.04          9.193  100.0
..                       ...         ...            ...    ...
295  IMG_20210721_102756.jpg        5.12          9.024  125.0
296  IMG_20210721_102758.jpg        5.12          9.024  125.0
297  IMG_20210721_102759.jpg        5.15          9.024  125.0
298  IMG_20210721_102801.jpg        5.15          8.976  100.0
299  IMG_20210721_102802.jpg        5.08          8.936  125.0

[300 rows x 4 columns]

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import glob
import pandas as pd
from PIL import Image
from PIL.ExifTags import TAGS

path="/content/drive/My Drive/Final Year Research/Dataset/Oneplus 5T/Level 03/*"
len_str_remove=len(path)-1

i=0
for file in glob.glob(path):
    #print(file[len_str_remove:])
    img = Image.open(file)
    # extract EXIF data
    exifdata = img.getexif()
    img_mdata=np.zeros(3)
    # iterating over all EXIF data fields
    for tag_id in exifdata:
        # get the tag name, instead of human unreadable tag id
        tag = TAGS.get(tag_id, tag_id)
        data = exifdata.get(tag_id)
        # decode bytes 
        if isinstance(data, bytes):
            data = data.decode()
        print(f"{tag:25}: {data}")
        if(tag=='BrightnessValue'):
          img_mdata[0]=data[0]/data[1]
        
        if(tag=='ShutterSpeedValue'):
          img_mdata[1]=data[0]/data[1]

        if(tag=='ISOSpeedRatings'):
          img_mdata[2]=data

    df.loc[150+i] = [file[len_str_remove:]] + [img_mdata[0]] + [img_mdata[1]] + [img_mdata[2]]
    i+=1
    if(i==1):break