In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [36]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import glob
import pandas as pd
from PIL import Image
from PIL.ExifTags import TAGS
import piexif

path="/content/drive/My Drive/Final Year Research/Dataset/Oneplus 5T/Level 05/*"
len_str_remove=len(path)-1
df = pd.DataFrame(columns=['image', 'brightness','shutter_speed','exposure_time','iso'])
ind=len(df)
i=0
for file in glob.glob(path):
  # iterating over all EXIF data fields
  img = Image.open(file)
  for tag_id in exifdata:
      # get the tag name, instead of human unreadable tag id
      tag = TAGS.get(tag_id, tag_id)
      data = exifdata.get(tag_id)
      # decode bytes 
      if isinstance(data, bytes):
          data = data.decode('latin-1')
      #print(f"{tag:25}: {data}")
      if(tag=='BrightnessValue'):
        img_mdata[0]=data[0]/data[1]
      
      if(tag=='ShutterSpeedValue'):
        img_mdata[1]=data[0]/data[1]

      if(tag=='ExposureTime'):
        img_mdata[2]=data[0]/data[1]
      
      if(tag=='ISOSpeedRatings'):
        img_mdata[3]=data
  df.loc[i] = [file[len_str_remove:]] + [img_mdata[0]] + [img_mdata[1]] + [img_mdata[2]] + [img_mdata[3]]
  i+=1

df

                       image  brightness  shutter_speed  exposure_time    iso
0    IMG_20210721_095141.jpg        4.97          9.024       0.001919  125.0
1    IMG_20210721_095142.jpg        4.97          9.024       0.001919  125.0
2    IMG_20210721_095144.jpg        4.97          9.024       0.001919  125.0
3    IMG_20210721_095145.jpg        4.97          9.024       0.001919  125.0
4    IMG_20210721_095146.jpg        4.97          9.024       0.001919  125.0
..                       ...         ...            ...            ...    ...
189  IMG_20210721_100338.jpg        4.97          9.024       0.001919  125.0
190  IMG_20210721_100339.jpg        4.97          9.024       0.001919  125.0
191  IMG_20210721_100342.jpg        4.97          9.024       0.001919  125.0
192  IMG_20210721_100343.jpg        4.97          9.024       0.001919  125.0
193  IMG_20210721_100346.jpg        4.97          9.024       0.001919  125.0

[194 rows x 5 columns]

In [37]:
len(df)

194

In [38]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import glob
import pandas as pd
from PIL import Image
from PIL.ExifTags import TAGS

path="/content/drive/My Drive/Final Year Research/Dataset/Oneplus 5T/Level 04/*"
len_str_remove=len(path)-1
ind=len(df)
i=0
for file in glob.glob(path):
  # iterating over all EXIF data fields
  img = Image.open(file)
  for tag_id in exifdata:
      # get the tag name, instead of human unreadable tag id
      tag = TAGS.get(tag_id, tag_id)
      data = exifdata.get(tag_id)
      # decode bytes 
      if isinstance(data, bytes):
          data = data.decode('latin-1')
      #print(f"{tag:25}: {data}")
      if(tag=='BrightnessValue'):
        img_mdata[0]=data[0]/data[1]
      
      if(tag=='ShutterSpeedValue'):
        img_mdata[1]=data[0]/data[1]

      if(tag=='ExposureTime'):
        img_mdata[2]=data[0]/data[1]
      
      if(tag=='ISOSpeedRatings'):
        img_mdata[3]=data
  df.loc[ind+i] = [file[len_str_remove:]] + [img_mdata[0]] + [img_mdata[1]] + [img_mdata[2]] + [img_mdata[3]]
  i+=1

df
print(df.shape)
df

(388, 5)

                       image  brightness  shutter_speed  exposure_time    iso
0    IMG_20210721_095141.jpg        4.97          9.024       0.001919  125.0
1    IMG_20210721_095142.jpg        4.97          9.024       0.001919  125.0
2    IMG_20210721_095144.jpg        4.97          9.024       0.001919  125.0
3    IMG_20210721_095145.jpg        4.97          9.024       0.001919  125.0
4    IMG_20210721_095146.jpg        4.97          9.024       0.001919  125.0
..                       ...         ...            ...            ...    ...
383  IMG_20210721_100338.jpg        4.97          9.024       0.001919  125.0
384  IMG_20210721_100339.jpg        4.97          9.024       0.001919  125.0
385  IMG_20210721_100342.jpg        4.97          9.024       0.001919  125.0
386  IMG_20210721_100343.jpg        4.97          9.024       0.001919  125.0
387  IMG_20210721_100346.jpg        4.97          9.024       0.001919  125.0

[388 rows x 5 columns]

In [39]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import glob
import pandas as pd
from PIL import Image
from PIL.ExifTags import TAGS

path="/content/drive/My Drive/Final Year Research/Dataset/Oneplus 5T/Level 03/*"
len_str_remove=len(path)-1
ind=len(df)
i=0
for file in glob.glob(path):
    #print(file[len_str_remove:])
    img = Image.open(file)
    # extract EXIF data
    exifdata = img.getexif()
    img_mdata=np.zeros(4)
    # iterating over all EXIF data fields
    for tag_id in exifdata:
        # get the tag name, instead of human unreadable tag id
        tag = TAGS.get(tag_id, tag_id)
        data = exifdata.get(tag_id)
        # decode bytes 
        if isinstance(data, bytes):
            data = data.decode()
        #print(f"{tag:25}: {data}")
        if(tag=='BrightnessValue'):
          img_mdata[0]=data[0]/data[1]
        
        if(tag=='ShutterSpeedValue'):
          img_mdata[1]=data[0]/data[1]

        if(tag=='ExposureTime'):
          img_mdata[2]=data[0]/data[1]
        
        if(tag=='ISOSpeedRatings'):
          img_mdata[3]=data

    df.loc[ind+i] = [file[len_str_remove:]] + [img_mdata[0]] + [img_mdata[1]] + [img_mdata[2]] + [img_mdata[3]]
    i+=1
    if(i==194):break

print(df.shape)
df

(582, 5)

                       image  brightness  shutter_speed  exposure_time    iso
0    IMG_20210721_095141.jpg        4.97          9.024       0.001919  125.0
1    IMG_20210721_095142.jpg        4.97          9.024       0.001919  125.0
2    IMG_20210721_095144.jpg        4.97          9.024       0.001919  125.0
3    IMG_20210721_095145.jpg        4.97          9.024       0.001919  125.0
4    IMG_20210721_095146.jpg        4.97          9.024       0.001919  125.0
..                       ...         ...            ...            ...    ...
577  IMG_20210721_102937.jpg        5.34          9.323       0.001560  125.0
578  IMG_20210721_102938.jpg        5.42          9.411       0.001468  125.0
579  IMG_20210721_102939.jpg        5.39          9.448       0.001431  100.0
580  IMG_20210721_102941.jpg        5.33          9.367       0.001515  125.0
581  IMG_20210721_102945.jpg        5.07          9.109       0.001808  125.0

[582 rows x 5 columns]

In [40]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import glob
import pandas as pd
from PIL import Image
from PIL.ExifTags import TAGS

path="/content/drive/My Drive/Final Year Research/Dataset/Oneplus 5T/Level 02/*"
len_str_remove=len(path)-1
ind=len(df)
i=0
for file in glob.glob(path):
    #print(file[len_str_remove:])
    img = Image.open(file)
    # extract EXIF data
    exifdata = img.getexif()
    img_mdata=np.zeros(4)
    # iterating over all EXIF data fields
    for tag_id in exifdata:
        # get the tag name, instead of human unreadable tag id
        tag = TAGS.get(tag_id, tag_id)
        data = exifdata.get(tag_id)
        # decode bytes 
        if isinstance(data, bytes):
            data = data.decode('latin-1')
        #print(f"{tag:25}: {data}")
        if(tag=='BrightnessValue'):
          img_mdata[0]=data[0]/data[1]
        
        if(tag=='ShutterSpeedValue'):
          img_mdata[1]=data[0]/data[1]

        if(tag=='ExposureTime'):
          img_mdata[2]=data[0]/data[1]
        
        if(tag=='ISOSpeedRatings'):
          img_mdata[3]=data

    df.loc[ind+i] = [file[len_str_remove:]] + [img_mdata[0]] + [img_mdata[1]] + [img_mdata[2]] + [img_mdata[3]]
    i+=1
    if(i==194):break

print(df.shape)
df

(776, 5)

                          image  brightness  ...  exposure_time    iso
0       IMG_20210721_095141.jpg        4.97  ...       0.001919  125.0
1       IMG_20210721_095142.jpg        4.97  ...       0.001919  125.0
2       IMG_20210721_095144.jpg        4.97  ...       0.001919  125.0
3       IMG_20210721_095145.jpg        4.97  ...       0.001919  125.0
4       IMG_20210721_095146.jpg        4.97  ...       0.001919  125.0
..                          ...         ...  ...            ...    ...
771  IMG_20210721_105534_01.jpg        5.17  ...       0.001709  100.0
772     IMG_20210721_105535.jpg        5.19  ...       0.001653  125.0
773     IMG_20210721_105537.jpg        5.13  ...       0.001709  100.0
774  IMG_20210721_105537_01.jpg        5.13  ...       0.001709  100.0
775     IMG_20210721_105538.jpg        5.14  ...       0.001709  100.0

[776 rows x 5 columns]

In [41]:
df.to_csv('metadata.csv',index=False)
!cp metadata.csv "drive/My Drive/Final Year Research/Dataset/Oneplus 5T/data_files/"

In [42]:
data=pd.read_csv('metadata.csv')
data

                          image  brightness  ...  exposure_time    iso
0       IMG_20210721_095141.jpg        4.97  ...       0.001919  125.0
1       IMG_20210721_095142.jpg        4.97  ...       0.001919  125.0
2       IMG_20210721_095144.jpg        4.97  ...       0.001919  125.0
3       IMG_20210721_095145.jpg        4.97  ...       0.001919  125.0
4       IMG_20210721_095146.jpg        4.97  ...       0.001919  125.0
..                          ...         ...  ...            ...    ...
771  IMG_20210721_105534_01.jpg        5.17  ...       0.001709  100.0
772     IMG_20210721_105535.jpg        5.19  ...       0.001653  125.0
773     IMG_20210721_105537.jpg        5.13  ...       0.001709  100.0
774  IMG_20210721_105537_01.jpg        5.13  ...       0.001709  100.0
775     IMG_20210721_105538.jpg        5.14  ...       0.001709  100.0

[776 rows x 5 columns]

In [44]:
#creating features file
df=pd.read_csv("drive/My Drive/Final Year Research/Dataset/Oneplus 5T/data_files/rgbarray.csv")
df['brightness']=data['brightness']
df['shutter_speed']=data['shutter_speed']
df['exposure_time']=data['exposure_time']
df['iso']=data['iso']

#write to csv
df.to_csv("drive/My Drive/Final Year Research/Dataset/Oneplus 5T/data_files/features.csv",index=False)

In [45]:
df=pd.read_csv("drive/My Drive/Final Year Research/Dataset/Oneplus 5T/data_files/features.csv")
df

       red_val   green_val   blue_val  ...  shutter_speed  exposure_time    iso
0    61.841728   83.685791  30.381555  ...          9.024       0.001919  125.0
1    58.776155   80.259737  28.989622  ...          9.024       0.001919  125.0
2    57.559864   79.052525  28.126113  ...          9.024       0.001919  125.0
3    58.090181   78.781991  31.884950  ...          9.024       0.001919  125.0
4    57.787745   78.502028  30.747365  ...          9.024       0.001919  125.0
..         ...         ...        ...  ...            ...            ...    ...
771  82.194736  102.484696  31.684638  ...          9.193       0.001709  100.0
772  81.049292  101.100902  31.487134  ...          9.240       0.001653  125.0
773  80.883341  101.111931  29.385463  ...          9.193       0.001709  100.0
774  80.806641  100.844573  29.671693  ...          9.193       0.001709  100.0
775  81.288360  101.317141  30.076289  ...          9.193       0.001709  100.0

[776 rows x 7 columns]

In [3]:
from PIL import Image
from PIL.ExifTags import TAGS

img = Image.open('/content/drive/My Drive/Final Year Research/Dataset/Oneplus 5T/Level 04/IMG_20210721_100334.jpg')

# extract EXIF data
exifdata = img.getexif()
# iterating over all EXIF data fields
for tag_id in exifdata:
    # get the tag name, instead of human unreadable tag id
    tag = TAGS.get(tag_id, tag_id)
    data = exifdata.get(tag_id)
    # decode bytes 
    if isinstance(data, bytes):
        data = data.decode()

    print(f"{tag:25}: {data}")

ExifVersion              : 0220
ComponentsConfiguration  :  
ShutterSpeedValue        : (8936, 1000)
DateTimeOriginal         : 2021:07:21 10:03:34
DateTimeDigitized        : 2021:07:21 10:03:34
ApertureValue            : (153, 100)
BrightnessValue          : (482, 100)
MeteringMode             : 0
FlashPixVersion          : 0100
Flash                    : 16
FocalLength              : (4103, 1000)
ColorSpace               : 1
ExifImageWidth           : 4608
ExifInteroperabilityOffset: 739
FocalLengthIn35mmFilm    : 24
SceneCaptureType         : 0
SubsecTime               : 501006
SubsecTimeOriginal       : 501006
SubsecTimeDigitized      : 501006
ExifImageHeight          : 3456
Model                    : ONEPLUS A5010
YCbCrPositioning         : 1
Make                     : OnePlus
SensingMethod            : 2
ExposureTime             : (1, 490)
XResolution              : (72, 1)
YResolution              : (72, 1)
FNumber                  : (170, 100)
SceneType                : 
ExposureProgram          : 0
GPSInfo                  : {1: 'N', 2: ((6, 1), (4, 1), (210532, 10000)), 3: 'E', 4: ((80, 1), (14, 1), (98537, 10000)), 5: b'\x01', 6: (86696, 1000), 7: ((4, 1), (33, 1), (34, 1)), 29: '2021:07:21'}
ISOSpeedRatings          : 125
ResolutionUnit           : 2
ExposureMode             : 0
WhiteBalance             : 0
Software                 : OnePlus5T-user 10 QKQ1.191014.012 2010292059 release-keys
DateTime                 : 2021:07:21 10:03:34
ExifOffset               : 250
MakerNote                : MM *         3AD     

In [26]:
from PIL import Image
from PIL.ExifTags import TAGS

# extract EXIF data
exifdata = img.getexif()
img_mdata=np.zeros(4)

df = pd.DataFrame(columns=['image', 'brightness','shutter_speed','exposure_time','iso'])

path="/content/drive/My Drive/Final Year Research/Dataset/Oneplus 5T/Level 02/*"

len_str_remove=len(path)-1
ind=len(df)
i=0
for file in glob.glob(path):
  # iterating over all EXIF data fields
  img = Image.open(file)
  for tag_id in exifdata:
      # get the tag name, instead of human unreadable tag id
      tag = TAGS.get(tag_id, tag_id)
      data = exifdata.get(tag_id)
      # decode bytes 
      if isinstance(data, bytes):
          data = data.decode('latin-1')
      #print(f"{tag:25}: {data}")
      if(tag=='BrightnessValue'):
        img_mdata[0]=data[0]/data[1]
      
      if(tag=='ShutterSpeedValue'):
        img_mdata[1]=data[0]/data[1]

      if(tag=='ExposureTime'):
        img_mdata[2]=data[0]/data[1]
      
      if(tag=='ISOSpeedRatings'):
        img_mdata[3]=data
  df.loc[i] = [file[len_str_remove:]] + [img_mdata[0]] + [img_mdata[1]] + [img_mdata[2]] + [img_mdata[3]]
  i+=1

df

                       image  brightness  shutter_speed  exposure_time    iso
0    IMG_20210721_103515.jpg        5.32          9.323        0.00156  125.0
1    IMG_20210721_103517.jpg        5.32          9.323        0.00156  125.0
2    IMG_20210721_103520.jpg        5.32          9.323        0.00156  125.0
3    IMG_20210721_103522.jpg        5.32          9.323        0.00156  125.0
4    IMG_20210721_103528.jpg        5.32          9.323        0.00156  125.0
..                       ...         ...            ...            ...    ...
195  IMG_20210721_105545.jpg        5.32          9.323        0.00156  125.0
196  IMG_20210721_104102.jpg        5.32          9.323        0.00156  125.0
197  IMG_20210721_104106.jpg        5.32          9.323        0.00156  125.0
198  IMG_20210721_104243.jpg        5.32          9.323        0.00156  125.0
199  IMG_20210721_104244.jpg        5.32          9.323        0.00156  125.0

[200 rows x 5 columns]